name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP: ${{ contains(github.event.commit.message, '#skip')}}

jobs:
  simple_pipeline_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Building
        run: npm run build
      - name: Testing
        run: npm run test
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && SKIP == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  tag_release:
    needs: simple_pipeline_job
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Tag release
      if: ${{ github.event_name == 'push' && SKIP == 'false' }}
      uses: anothrNick/github-tag-action@1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        DRY_RUN: true